export const environment = {
  production: false,
  apiKey: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzODk3MjExZi04ZjFjLTRlMTUtYTdiMS0wZGZkNDFjNjc5NDciLCJlbWFpbCI6InRlc3RlQGV4YW1wbGUuY29tIiwiZ2l2ZW5fbmFtZSI6InRlc3RlIiwibmJmIjoxNjk2OTM0MjYzLCJleHAiOjE2OTY5NjMwNjMsImlhdCI6MTY5NjkzNDI2MywiaXNzIjoiZUFnZW5kYSIsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3QifQ.TOzLwhsCsKt6wgjQtzAt_wvmKg7HDXleCAHVIn7DHcU',
};
